# -*- coding: utf-8 -*-
"""asses-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nUIUlCGj8mHizKzpLYJCVZbUymtJp_qE
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

print(sns.get_dataset_names())

df=sns.load_dataset('car_crashes')

df

df.info()

sns.scatterplot(x="speeding",y="alcohol",data=df)

#inference: alcohol consumption is more then results in increase of speed.

sns.jointplot(x="speeding",y="alcohol",data=df)

#inference:analyzes the drinking and speeding whenever they got caught into an accident.

sns.displot(df["not_distracted"])

#inference:the accidents in which persons are not distracted.

sns.kdeplot(df["alcohol"])

#inference:crashes in regard to alochol usage.

sns.pairplot(df)

#inference: plotting the relationships across the entire data

sns.lineplot(x="alcohol",y="no_previous",data=df)

#inference: high intake of alcohol results in the persons involved in previous accidents.

sns.barplot(x="abbrev",y="alcohol",data=df)

#inference: data visualization of consumption of alochol according to different states.

sns.relplot(df["total"])

#inference: Number of drivers involved in fatal collisions per billion miles

sns.lineplot(x="ins_losses",y="ins_premium",data=df)

#inference:Car Insurance Premiums increases in increase with Losses incurred by insurance companies for collisions per insured driver

sns.countplot(x="no_previous",data=df)

#inference:a data visualization of the Drivers involved in fatal collisions who had not been involved in any previous accidents.

sns.boxplot(x="total",y="not_distracted",data=df)

#inference:a box plot of total number of drivers involved in fatal collisions per billion miles vs  Percentage Of drivers involved in fatal collisions who were not distracted

corr=df.corr()
corr

sns.heatmap(corr,annot=True,cmap="YlGnBu")

#inference:a heat map representation of car_crashes corr data